## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'keithley'  #for instance daqmx
package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_keithley' #to modify
description = 'Set of PyMoDAQ plugins for various physical measurements from keithley'

author = 'Sébastien Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ["pyvisa", "pymeasure", 'pymodaq>=4.0']