[INSTRUMENT]
# Instrument in wich is plugged your switching module (called 1111 here)
# (e.g.: "ASRL1::INSTR", "TCPIP::192.168.01.01::1394::SOCKET")
rsrc_name = "TCPIP::192.168.01.01::1394::SOCKET"

[MODULE]
module_name = 1111

[CHANNELS]
## Thermocouple config example
[CHANNELS.101]
mode = "temp"
transducer = "tc"
type = "K"
ref_junction = "int"
resolution = 6
nplc = 5

[CHANNELS.102]
mode = "temp"
transducer = "tc"
type = "K"
ref_junction = "int"
resolution = 6
nplc = 5

[CHANNELS.103]

[CHANNELS.104]

[CHANNELS.105]

[CHANNELS.106]

[CHANNELS.107]

[CHANNELS.108]

[CHANNELS.109]

[CHANNELS.110]

[CHANNELS.111]

[CHANNELS.112]

[CHANNELS.113]

[CHANNELS.114]

[CHANNELS.115]

[CHANNELS.116]

[CHANNELS.117]

[CHANNELS.118]

[CHANNELS.119]

[CHANNELS.120]