[INSTRUMENT]
# Instrument in wich is plugged the 7708 switching module
# (e.g.: "ASRL1::INSTR", "TCPIP::192.168.01.01::1394::SOCKET")
rsrc_name = "ASRL1::INSTR"

[MODULE]
module_name = 7708

[CHANNELS]
## Thermocouple config example
[CHANNELS.101]
mode = "temp"
transducer = "tc"
type = "K"
ref_junction = "int"
resolution = 6
nplc = 5

[CHANNELS.102]
mode = "temp"
transducer = "tc"
type = "K"
ref_junction = "int"
resolution = 6
nplc = 5

[CHANNELS.103]

[CHANNELS.104]

[CHANNELS.105]

[CHANNELS.106]

[CHANNELS.107]

[CHANNELS.108]

[CHANNELS.109]

[CHANNELS.110]

[CHANNELS.111]

[CHANNELS.112]

[CHANNELS.113]

[CHANNELS.114]

[CHANNELS.115]

[CHANNELS.116]

[CHANNELS.117]

[CHANNELS.118]

[CHANNELS.119]

[CHANNELS.120]

[CHANNELS.121]

[CHANNELS.122]

[CHANNELS.123]

[CHANNELS.124]

[CHANNELS.125]

[CHANNELS.126]

[CHANNELS.127]

[CHANNELS.128]

[CHANNELS.129]

[CHANNELS.130]

[CHANNELS.131]

[CHANNELS.132]

[CHANNELS.133]

[CHANNELS.134]

[CHANNELS.135]

[CHANNELS.136]

[CHANNELS.137]

[CHANNELS.138]

[CHANNELS.139]

[CHANNELS.140]